version: "3.8"
services:
  app:
    container_name: app
    build: "."
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    env_file:
      - .env
    depends_on:
      - "postgres"
    networks:
      - app

  postgres:
    container_name: postgres
    image:
      postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    networks:
      - app

networks:
   app: